name: projectmanagement-depl
on:
  push: 
    branches:
      - main
    paths:
      - "projectmanagement/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ProjectManagement && docker build -t longle2003/projectmanagement .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push longle2003/projectmanagement